export const stations: { [key: string]: string } = {
  PE: 'Pl. Espanya',
  MG: 'Magòria La Campana',
  IC: 'Ildefons Cerdà',
  EU: 'Europa | Fira',
  GO: 'Gornal',
  SP: 'Sant Josep',
  LH: "L'Hospitalet Av. Carrilet",
  AL: 'Almeda',
  CO: 'Cornellà Riera',
  BO: 'Sant Boi',
  ML: 'Molí Nou - Ciutat Cooperativa',
  CG: 'Colònia Güell',
  CL: 'Santa Coloma de Cervelló',
  VH: 'Sant Vicenç dels Horts',
  CR: 'Can Ros',
  QC: 'Quatre Camins',
  PA: 'Pallejà',
  SA: 'Sant Andreu de la Barca',
  PL: 'El Palau',
  MV: 'Martorell Vila | Castellbisbal',
  MC: 'Martorell Central',
  ME: 'Martorell Enllaç',
  //
  AB: 'Abrera',
  OL: 'Olesa de Montserrat',
  AE: 'Aeri de Montserrat',
  MO: 'Monistrol de Montserrat',
  CB: 'Castellbell i El Vilar',
  SV: 'Sant Vicenç | Castellgalí',
  VI: 'Manresa-Viladordis',
  MA: 'Manresa-Alta',
  MB: 'Manresa-Baixador',
  //
  SE: 'Sant Esteve Sesrovires',
  BE: 'La Beguda',
  CP: 'Can Parellada',
  MQ: 'Masquefa',
  PI: 'Piera',
  VA: "Vallbona d'Anoia",
  CA: 'Capellades',
  PO: 'La Pobla de Claramunt',
  VN: 'Vilanova del Camí',
  IG: 'Igualada'
}
