// Generated by scripts/extract-e8-timetable.mjs from
// docs/timetables/Horari_e8_2019_.pdf — do not edit by hand.
//
// Re-run the script when AMB publishes a new poster. There is no e8 API to check
// this against, so the printed sheet is the only source; the extractor self-checks
// against the expedition counts on the poster and refuses to emit anything if the
// layout has moved.

/** fromBarcelona is Francesc Macia -> Corbera; toBarcelona is the way back. */
export type E8Direction = 'toBarcelona' | 'fromBarcelona'

export type E8DayType = 'weekday' | 'saturday' | 'sundayHoliday' | 'christmas'

/** Both directions are indexed in this order, Barcelona-first. */
export const E8_STOPS = [
  'FM',
  'MARIA_CRISTINA',
  'MOLINS',
  'QC',
  'PALMA',
  'CORBERA_BAIXA',
  'CORBERA_ALTA'
] as const

export interface E8Trip {
  /**
   * Minutes past midnight per stop, in E8_STOPS order. null means the bus does
   * not call there — most expeditions skip Molins de Rei. Times after midnight
   * stay above 1440, as the Saturday night runs do.
   */
  stops: (number | null)[]
  /** (1) Does not run during August. */
  notInAugust?: boolean
  /** (2) Runs on school days only, per Barcelona's school calendar. */
  schoolDaysOnly?: boolean
  /** (3) Runs every Saturday of the year, holidays included. */
  everySaturday?: boolean
  /** (4) Starts or finishes at Molins de Rei rather than running the full line. */
  endsAtMolins?: boolean
  /** (5) Runs via Sant Feliu, Sant Just and Esplugues instead of the motorway. */
  viaSantFeliu?: boolean
}

const n = null

export const e8Timetable: Record<E8DayType, Record<E8Direction, E8Trip[]>> = {
  weekday: {
    toBarcelona: [
      { stops: [392, 385, 368, 363, 357, 350, 340] },
      { stops: [412, 405, 388, 383, 377, 370, 360], notInAugust: true },
      { stops: [428, 421, 404, 398, 392, 385, 375] },
      { stops: [n, 430, n, 409, 403, 395, n], notInAugust: true },
      { stops: [445, 438, n, 414, 408, 400, 390], notInAugust: true },
      { stops: [452, 445, n, 421, 413, 405, n], notInAugust: true },
      { stops: [457, 450, n, 426, 418, 410, 400], schoolDaysOnly: true },
      { stops: [467, 460, n, 431, 423, 415, 405] },
      { stops: [477, 470, n, 441, 433, 425, 415] },
      { stops: [482, 475, n, 446, 438, 430, 420], schoolDaysOnly: true },
      { stops: [495, 487, n, 456, 448, 440, 430], notInAugust: true },
      { stops: [513, 505, 472, 466, 458, 450, 440] },
      { stops: [515, 507, n, 476, 468, 460, 450], notInAugust: true },
      { stops: [n, 517, n, 486, 478, 470, 460], notInAugust: true },
      { stops: [538, 528, n, 496, 488, 480, 470] },
      { stops: [548, 538, n, 506, 498, 490, 480], notInAugust: true },
      { stops: [558, 548, n, 516, 508, 500, 490], schoolDaysOnly: true },
      { stops: [566, 556, n, 526, 518, 510, 500] },
      { stops: [578, 568, 543, 536, 528, 520, 510], notInAugust: true },
      { stops: [584, 574, n, 546, 538, 530, 520], notInAugust: true },
      { stops: [594, 584, 563, 556, 548, 540, 530] },
      { stops: [602, 592, n, 571, 563, 555, 545], notInAugust: true },
      { stops: [618, 608, n, 586, 578, 570, 560] },
      { stops: [630, 622, n, 601, 593, 585, 575] },
      { stops: [645, 637, n, 616, 608, 600, 590], notInAugust: true },
      { stops: [663, 655, 636, 630, 622, 615, 605] },
      { stops: [686, 678, n, 660, 652, 645, 635], schoolDaysOnly: true },
      { stops: [701, 693, n, 675, 667, 660, 650] },
      { stops: [716, 708, n, 690, 682, 675, 665], notInAugust: true },
      { stops: [752, 744, 726, 720, 712, 705, 695] },
      { stops: [774, 766, n, 750, 742, 735, 725], notInAugust: true },
      { stops: [789, 781, n, 765, 757, 750, 740] },
      { stops: [798, 790, n, 774, 767, 760, 750], notInAugust: true },
      { stops: [808, 800, n, 784, 777, 770, 760], schoolDaysOnly: true },
      { stops: [818, 810, n, 794, 787, 780, 770] },
      { stops: [833, 825, n, 809, 802, 795, 785], notInAugust: true },
      { stops: [848, 840, n, 824, 817, 810, 800] },
      { stops: [863, 855, n, 839, 832, 825, 815], schoolDaysOnly: true },
      { stops: [873, 865, n, 849, 842, 835, 825], notInAugust: true },
      { stops: [883, 875, n, 859, 852, 845, 835], notInAugust: true },
      { stops: [893, 885, n, 869, 862, 855, 845], schoolDaysOnly: true },
      { stops: [909, 900, n, 884, 877, 870, 860] },
      { stops: [924, 915, n, 899, 892, 885, 875] },
      { stops: [941, 932, n, 914, 907, 900, 890], notInAugust: true },
      { stops: [951, 942, n, 924, 917, 910, 900], notInAugust: true },
      { stops: [961, 952, n, 934, 927, 920, 910], schoolDaysOnly: true },
      { stops: [974, 965, 949, 944, 937, 930, 920] },
      { stops: [986, 977, n, 959, 952, 945, 935], schoolDaysOnly: true },
      { stops: [1001, 992, n, 974, 967, 960, 950] },
      { stops: [1011, 1002, n, 984, 977, 970, 960], notInAugust: true },
      { stops: [1021, 1012, n, 994, 987, 980, 970], schoolDaysOnly: true },
      { stops: [1038, 1029, 1011, 1005, 997, 990, 980] },
      { stops: [1047, 1038, n, 1020, 1012, 1005, 995] },
      { stops: [1073, 1064, 1043, 1035, 1027, 1020, 1010] },
      { stops: [1074, 1065, n, 1044, 1037, 1030, 1020], schoolDaysOnly: true },
      { stops: [1084, 1075, n, 1054, 1047, 1040, 1030], notInAugust: true },
      { stops: [1094, 1085, n, 1064, 1057, 1050, 1040], notInAugust: true },
      { stops: [1104, 1095, n, 1074, 1067, 1060, 1050], schoolDaysOnly: true },
      { stops: [1114, 1105, n, 1084, 1077, 1070, 1060] },
      { stops: [1128, 1119, n, 1094, 1087, 1080, 1070], schoolDaysOnly: true },
      { stops: [1139, 1130, n, 1109, 1102, 1095, 1085], notInAugust: true },
      { stops: [1154, 1145, n, 1124, 1117, 1110, 1100] },
      { stops: [1168, 1159, n, 1139, 1132, 1125, 1115], notInAugust: true },
      { stops: [1189, 1180, 1160, 1154, 1147, 1140, 1130] },
      { stops: [1192, 1183, n, 1164, 1157, 1150, 1140] },
      { stops: [1209, 1203, n, 1184, 1177, 1170, 1160] },
      { stops: [1219, 1213, n, 1194, 1187, 1180, 1170], schoolDaysOnly: true },
      { stops: [1229, 1223, n, 1204, 1197, 1190, 1180], notInAugust: true },
      { stops: [1251, 1245, 1229, 1224, 1217, 1210, 1200] },
      { stops: [1281, 1275, n, 1259, 1252, 1245, 1235] },
      { stops: [1311, 1305, n, 1289, 1282, 1275, 1265] },
      { stops: [1338, 1332, 1317, 1312, 1305, 1299, 1290] },
      { stops: [1393, 1387, 1372, 1367, 1360, 1354, 1345] }
    ],
    fromBarcelona: [
      { stops: [405, 410, 427, 430, 436, 446, 460] },
      { stops: [435, 440, n, 455, 461, 471, 485] },
      { stops: [450, 455, n, 470, 476, 486, 500], notInAugust: true },
      { stops: [465, 470, 487, 490, 496, 506, 520] },
      { stops: [495, 500, 520, 523, 529, 539, 553], notInAugust: true },
      { stops: [525, 530, n, 548, 554, 564, 578] },
      { stops: [550, 555, 572, 575, 581, 591, 605] },
      { stops: [570, 575, n, 590, 596, 606, 620], schoolDaysOnly: true },
      { stops: [585, 590, 607, 610, 616, 626, 640] },
      { stops: [600, 605, n, 620, 626, 636, 650], notInAugust: true },
      { stops: [615, 620, n, 635, 641, 651, 665], notInAugust: true },
      { stops: [630, 635, n, 650, 656, 666, 680] },
      { stops: [645, 650, n, 665, 671, 681, 695] },
      { stops: [660, 665, 682, 685, 691, 701, 715] },
      { stops: [675, 680, n, 695, 701, 711, 725], notInAugust: true },
      { stops: [700, 705, n, 721, 727, 737, 751], notInAugust: true },
      { stops: [720, 725, n, 741, 747, 757, 771], schoolDaysOnly: true },
      { stops: [735, 740, n, 756, 762, 772, 786] },
      { stops: [750, 755, n, 771, 777, 787, 801], notInAugust: true },
      { stops: [765, 770, n, 786, 792, 802, 816] },
      { stops: [780, 785, n, 801, 807, 817, 831], notInAugust: true },
      { stops: [795, 800, n, 816, 822, 832, 846] },
      { stops: [810, 815, n, 832, 838, 848, 862], notInAugust: true },
      { stops: [820, 825, n, 842, 848, 858, 872], schoolDaysOnly: true },
      { stops: [830, 835, n, 852, 858, 868, 882] },
      { stops: [840, 845, n, 862, 868, 878, 892], notInAugust: true },
      { stops: [850, 855, n, 872, 878, 888, 902], schoolDaysOnly: true },
      { stops: [860, 865, 882, 885, 891, 901, 915] },
      { stops: [870, 875, n, 892, 898, 908, 922], schoolDaysOnly: true },
      { stops: [880, 885, n, 902, 908, 918, 932], notInAugust: true },
      { stops: [890, 895, 912, 915, 921, 931, 945] },
      { stops: [900, 905, n, 920, 926, 936, 950], notInAugust: true },
      { stops: [910, 915, n, 930, 936, 946, 960] },
      { stops: [920, 925, n, 940, 946, 956, 970], schoolDaysOnly: true },
      { stops: [930, 935, n, 950, 956, 966, 980] },
      { stops: [945, 950, 967, 970, 976, 986, 1000], notInAugust: true },
      { stops: [960, 965, n, 980, 986, 996, 1010], notInAugust: true },
      { stops: [970, 975, n, 990, 996, 1006, 1020], schoolDaysOnly: true },
      { stops: [980, 985, 1002, 1005, 1011, 1021, 1035] },
      { stops: [995, 1000, n, 1017, 1023, 1033, 1047], schoolDaysOnly: true },
      { stops: [1010, 1015, n, 1032, 1038, 1048, 1062] },
      { stops: [1025, 1030, n, 1047, 1053, 1063, 1077], schoolDaysOnly: true },
      { stops: [1035, 1040, n, 1057, 1063, 1073, 1087], notInAugust: true },
      { stops: [1045, 1050, 1069, 1072, 1078, 1088, 1102] },
      { stops: [1055, 1060, n, 1077, 1083, 1093, 1107], notInAugust: true },
      { stops: [1070, 1075, n, 1092, 1098, 1108, 1122] },
      { stops: [1080, 1085, n, 1102, 1108, 1118, 1132], schoolDaysOnly: true },
      { stops: [1090, 1095, 1114, 1117, 1123, 1133, 1147] },
      { stops: [1100, 1105, n, 1122, 1128, 1138, 1152], notInAugust: true },
      { stops: [1110, 1115, n, 1132, 1138, 1148, 1162], notInAugust: true },
      { stops: [1120, 1125, n, 1142, 1148, 1158, 1172], schoolDaysOnly: true },
      { stops: [1130, 1135, n, 1152, 1158, 1168, 1182] },
      { stops: [1140, 1145, n, 1162, 1168, 1178, 1192], schoolDaysOnly: true },
      { stops: [1150, 1155, n, 1172, 1178, 1188, 1202], notInAugust: true },
      { stops: [1165, 1170, n, 1187, 1193, 1203, 1217] },
      { stops: [1180, 1185, n, 1202, 1208, 1218, 1232], notInAugust: true },
      { stops: [1190, 1195, 1212, 1215, 1221, 1231, 1245] },
      { stops: [1200, 1205, n, 1222, 1228, 1238, 1252] },
      { stops: [1210, 1215, n, 1230, 1236, 1246, 1260], notInAugust: true },
      { stops: [1220, 1225, n, 1240, 1246, 1256, 1270], schoolDaysOnly: true },
      { stops: [1230, 1235, n, 1250, 1256, 1266, 1280] },
      { stops: [1245, 1250, n, 1265, 1271, 1281, 1295], schoolDaysOnly: true },
      { stops: [1260, 1265, n, 1280, 1286, 1296, 1310], notInAugust: true },
      { stops: [1275, 1280, n, 1295, 1301, 1311, 1325] },
      { stops: [1290, 1295, n, 1310, 1315, 1325, 1339] },
      { stops: [1325, 1330, n, 1345, 1350, 1360, 1374] },
      { stops: [1350, 1355, 1372, 1375, 1380, 1390, 1404] },
      { stops: [1410, 1415, 1432, 1435, 1440, 1450, 1464] }
    ]
  },
  saturday: {
    toBarcelona: [
      { stops: [418, 410, 397, 393, 385, 378, 370] },
      { stops: [475, 467, 450, 446, 438, 430, 420] },
      { stops: [515, 507, 490, 486, 478, 470, 460] },
      { stops: [555, 547, 530, 526, 518, 510, 500] },
      { stops: [590, 582, 565, 561, 553, 545, 535] },
      { stops: [625, 617, 600, 596, 588, 580, 570] },
      { stops: [665, 656, 637, 633, 624, 615, 605] },
      { stops: [700, 691, 672, 668, 659, 650, 640] },
      { stops: [735, 726, 707, 703, 694, 685, 675] },
      { stops: [770, 761, 742, 738, 729, 720, 710] },
      { stops: [805, 796, 777, 773, 764, 755, n] },
      { stops: [840, 831, 812, 808, 799, 790, 780] },
      { stops: [875, 866, 847, 843, 834, 825, 815] },
      { stops: [910, 901, 882, 878, 869, 860, 850] },
      { stops: [945, 936, 917, 913, 904, 895, 885] },
      { stops: [980, 971, 952, 948, 939, 930, 920] },
      { stops: [1015, 1006, 987, 983, 974, 965, 955] },
      { stops: [1050, 1041, 1022, 1018, 1009, 1000, 990] },
      { stops: [1085, 1076, 1057, 1053, 1044, 1035, 1025] },
      { stops: [1120, 1111, 1092, 1088, 1079, 1070, 1060] },
      { stops: [1155, 1146, 1127, 1123, 1114, 1105, 1095] },
      { stops: [1190, 1181, 1162, 1158, 1149, 1140, 1130] },
      { stops: [1225, 1216, 1197, 1193, 1184, 1175, 1165] },
      { stops: [1260, 1251, 1232, 1228, 1219, 1210, 1200] },
      { stops: [1295, 1286, 1267, 1263, 1254, 1245, 1235] },
      { stops: [1330, 1322, 1305, 1301, 1293, 1285, 1275] },
      { stops: [1445, 1440, 1426, 1420, 1412, 1404, 1395], everySaturday: true },
      { stops: [1565, 1560, 1546, 1540, 1532, 1524, 1515], everySaturday: true }
    ],
    fromBarcelona: [
      { stops: [430, 435, 450, 453, 459, 469, 484] },
      { stops: [480, 485, 500, 503, 509, 519, 534] },
      { stops: [525, 530, 546, 549, 555, 565, 580] },
      { stops: [565, 570, 586, 589, 595, 605, 620] },
      { stops: [600, 605, 621, 624, 630, 640, 655] },
      { stops: [635, 640, 656, 659, 665, 675, 690] },
      { stops: [670, 675, 691, 694, 700, 710, 725] },
      { stops: [705, 710, 726, 729, 735, 745, 760] },
      { stops: [740, 745, 761, 764, 770, 780, 795] },
      { stops: [775, 780, 796, 799, 805, 815, 830] },
      { stops: [810, 815, 831, 834, 840, 850, 865] },
      { stops: [845, 850, 866, 869, 875, 885, 900] },
      { stops: [880, 885, 901, 904, 910, 920, 935] },
      { stops: [915, 920, 936, 939, 945, 955, 970] },
      { stops: [950, 955, 971, 974, 980, 990, 1005] },
      { stops: [985, 990, 1006, 1009, 1015, 1025, 1040] },
      { stops: [1020, 1025, 1041, 1044, 1050, 1060, 1075] },
      { stops: [1055, 1060, 1076, 1079, 1085, 1095, 1110] },
      { stops: [1090, 1095, 1111, 1114, 1120, 1130, 1145] },
      { stops: [1125, 1130, 1146, 1149, 1155, 1165, 1180] },
      { stops: [1160, 1165, 1181, 1184, 1190, 1200, 1215] },
      { stops: [1195, 1200, 1216, 1219, 1225, 1235, 1250] },
      { stops: [1230, 1235, 1251, 1254, 1260, 1270, 1285] },
      { stops: [1265, 1270, 1286, 1289, 1295, 1305, 1320] },
      { stops: [1300, 1305, 1321, 1324, 1330, 1340, 1355] },
      { stops: [1340, 1345, 1360, 1363, 1369, 1379, 1394] },
      { stops: [1455, 1460, 1475, 1478, 1484, 1494, 1508], everySaturday: true },
      { stops: [1575, 1580, 1595, 1598, 1604, 1614, 1628], everySaturday: true }
    ]
  },
  sundayHoliday: {
    toBarcelona: [
      { stops: [n, n, 423, 419, 411, 404, 395], endsAtMolins: true },
      { stops: [510, 502, 485, 481, 473, 465, 455] },
      { stops: [570, 562, 545, 541, 533, 525, 515] },
      { stops: [630, 622, 605, 601, 593, 585, 575] },
      { stops: [695, 686, 666, 662, 653, 645, 635] },
      { stops: [755, 746, 726, 722, 713, 705, 695] },
      { stops: [815, 806, 786, 782, 773, 765, 755] },
      { stops: [875, 866, 846, 842, 833, 825, 815] },
      { stops: [950, 941, 921, 917, 908, 900, 890] },
      { stops: [1005, 996, 976, 972, 963, 955, 945] },
      { stops: [1055, 1046, 1026, 1022, 1013, 1005, 995] },
      { stops: [1100, 1091, 1071, 1067, 1058, 1050, 1040] },
      { stops: [1145, 1136, 1116, 1112, 1103, 1095, 1085] },
      { stops: [1195, 1186, 1166, 1162, 1153, 1145, 1135] },
      { stops: [1245, 1236, 1216, 1212, 1203, 1195, 1185] },
      { stops: [1290, 1282, 1265, 1261, 1253, 1245, 1235] },
      { stops: [1340, 1332, 1315, 1311, 1303, 1295, 1285] }
    ],
    fromBarcelona: [
      { stops: [n, n, 425, 428, 434, 444, 460], endsAtMolins: true },
      { stops: [525, 530, 545, 548, 554, 564, 580] },
      { stops: [585, 590, 605, 608, 614, 624, 640] },
      { stops: [645, 650, 665, 668, 674, 684, 700] },
      { stops: [700, 705, 721, 724, 730, 740, 757] },
      { stops: [760, 765, 781, 784, 790, 800, 817] },
      { stops: [820, 825, 841, 844, 850, 860, 877] },
      { stops: [890, 895, 911, 914, 920, 930, 947] },
      { stops: [955, 960, 976, 979, 985, 995, 1012] },
      { stops: [1010, 1015, 1031, 1034, 1040, 1050, 1067] },
      { stops: [1060, 1065, 1081, 1084, 1090, 1100, 1117] },
      { stops: [1105, 1110, 1126, 1129, 1135, 1145, 1162] },
      { stops: [1150, 1155, 1171, 1174, 1180, 1190, 1207] },
      { stops: [1200, 1205, 1221, 1224, 1230, 1240, 1257] },
      { stops: [1250, 1255, 1271, 1274, 1280, 1290, 1307] },
      { stops: [1300, 1305, 1321, 1324, 1330, 1340, 1357] },
      { stops: [1350, 1355, 1371, 1374, 1380, 1390, 1407] }
    ]
  },
  christmas: {
    toBarcelona: [
      { stops: [590, 585, 570, 565, 558, 550, 540] },
      { stops: [655, 650, 635, 630, 623, 615, 605] },
      { stops: [720, 715, 700, 695, 688, 680, 670] },
      { stops: [800, 795, 770, 765, 758, 750, 740] },
      { stops: [1080, 1075, 1050, 1045, 1038, 1030, 1020] },
      { stops: [1145, 1140, 1115, 1110, 1103, 1095, 1085] },
      { stops: [1215, 1210, 1185, 1180, 1173, 1165, 1155] },
      { stops: [1280, 1275, 1250, 1245, 1238, 1230, 1220], viaSantFeliu: true }
    ],
    fromBarcelona: [
      { stops: [595, 600, 620, 625, 630, 640, 652] },
      { stops: [660, 665, 690, 695, 700, 710, 722], viaSantFeliu: true },
      { stops: [740, 745, 765, 770, 775, 785, 797] },
      { stops: [810, 815, 835, 840, 845, 855, 867] },
      { stops: [1090, 1095, 1115, 1120, 1125, 1135, 1147] },
      { stops: [1155, 1160, 1175, 1180, 1185, 1195, 1207] }
    ]
  }
}
